/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mapzen.tangram;

public class ClientGeoJsonSource extends DataSource {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected ClientGeoJsonSource(long cPtr, boolean cMemoryOwn) {
    super(tangramJNI.ClientGeoJsonSource_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientGeoJsonSource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        tangramJNI.delete_ClientGeoJsonSource(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ClientGeoJsonSource(String _name, String _url) {
    this(tangramJNI.new_ClientGeoJsonSource(_name, _url), true);
  }

  public void addData(String _data) {
    tangramJNI.ClientGeoJsonSource_addData(swigCPtr, this, _data);
  }

  public void addPoint(Tags tags, double[] _coords) {
    tangramJNI.ClientGeoJsonSource_addPoint(swigCPtr, this, Tags.getCPtr(tags), tags, _coords);
  }

  public void addLine(Tags tags, double[] _coords, int _lineLength) {
    tangramJNI.ClientGeoJsonSource_addLine(swigCPtr, this, Tags.getCPtr(tags), tags, _coords, _lineLength);
  }

  public void addPoly(Tags tags, double[] _coords, int[] _ringLengths, int rings) {
    tangramJNI.ClientGeoJsonSource_addPoly(swigCPtr, this, Tags.getCPtr(tags), tags, _coords, _ringLengths, rings);
  }

  public void clearData() {
    tangramJNI.ClientGeoJsonSource_clearData(swigCPtr, this);
  }

}
