/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mapzen.tangram;

public class LngLat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LngLat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LngLat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TangramJNI.delete_LngLat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

    public LngLat set(double lng, double lat) {
         setLngLat(lng, lat);
         return this;
     }

  public LngLat() {
    this(TangramJNI.new_LngLat__SWIG_0(), true);
  }

  public LngLat(double _lon, double _lat) {
    this(TangramJNI.new_LngLat__SWIG_1(_lon, _lat), true);
  }

  public LngLat(LngLat _other) {
    this(TangramJNI.new_LngLat__SWIG_2(LngLat.getCPtr(_other), _other), true);
  }

  public LngLat set(LngLat _other) {
    return new LngLat(TangramJNI.LngLat_set__SWIG_0(swigCPtr, this, LngLat.getCPtr(_other), _other), false);
  }

  public boolean equals(LngLat _other) {
    return TangramJNI.LngLat_equals(swigCPtr, this, LngLat.getCPtr(_other), _other);
  }

  public void setLongitude(double value) {
    TangramJNI.LngLat_longitude_set(swigCPtr, this, value);
  }

  public double getLongitude() {
    return TangramJNI.LngLat_longitude_get(swigCPtr, this);
  }

  public void setLatitude(double value) {
    TangramJNI.LngLat_latitude_set(swigCPtr, this, value);
  }

  public double getLatitude() {
    return TangramJNI.LngLat_latitude_get(swigCPtr, this);
  }

  public void setLngLat(double lng, double lat) {
    TangramJNI.LngLat_setLngLat(swigCPtr, this, lng, lat);
  }

}
