/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mapzen.tangram;

public class Properties {
    private transient long swigCPtr;
    private transient boolean swigCMemOwn;

    protected Properties(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(Properties obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                TangramJNI.delete_Properties(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public Properties() {
        this(TangramJNI.new_Properties(), true);
    }

    public void clear() {
        TangramJNI.Properties_clear(swigCPtr, this);
    }

    public boolean contains(String key) {
        return TangramJNI.Properties_contains(swigCPtr, this, key);
    }

    public float getNumeric(String key) {
        return TangramJNI.Properties_getNumeric(swigCPtr, this, key);
    }

    public String getString(String key) {
        return TangramJNI.Properties_getString(swigCPtr, this, key);
    }

    public void add(String key, String value) {
        TangramJNI.Properties_add__SWIG_0(swigCPtr, this, key, value);
    }

    public void add(String key, float value) {
        TangramJNI.Properties_add__SWIG_1(swigCPtr, this, key, value);
    }

}
