/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mapzen.tangram;

public class Tags {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Tags(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tags obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TangramJNI.delete_Tags(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Tags() {
    this(TangramJNI.new_Tags__SWIG_0(), true);
  }

  public Tags(Tags arg0) {
    this(TangramJNI.new_Tags__SWIG_1(Tags.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return TangramJNI.Tags_size(swigCPtr, this);
  }

  public boolean empty() {
    return TangramJNI.Tags_empty(swigCPtr, this);
  }

  public void clear() {
    TangramJNI.Tags_clear(swigCPtr, this);
  }

  public String get(String key) {
    return TangramJNI.Tags_get(swigCPtr, this, key);
  }

  public void set(String key, String x) {
    TangramJNI.Tags_set(swigCPtr, this, key, x);
  }

  public void del(String key) {
    TangramJNI.Tags_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return TangramJNI.Tags_has_key(swigCPtr, this, key);
  }

}
