/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mapzen.tangram;

public class tangramJNI {
  public final static native long new_Properties();
  public final static native void Properties_clear(long jarg1, Properties jarg1_);
  public final static native boolean Properties_contains(long jarg1, Properties jarg1_, String jarg2);
  public final static native float Properties_getNumeric(long jarg1, Properties jarg1_, String jarg2);
  public final static native String Properties_getString(long jarg1, Properties jarg1_, String jarg2);
  public final static native void Properties_add__SWIG_0(long jarg1, Properties jarg1_, String jarg2, String jarg3);
  public final static native void Properties_add__SWIG_1(long jarg1, Properties jarg1_, String jarg2, float jarg3);
  public final static native void delete_Properties(long jarg1);
  public final static native long new_Tags__SWIG_0();
  public final static native long new_Tags__SWIG_1(long jarg1, Tags jarg1_);
  public final static native long Tags_size(long jarg1, Tags jarg1_);
  public final static native boolean Tags_empty(long jarg1, Tags jarg1_);
  public final static native void Tags_clear(long jarg1, Tags jarg1_);
  public final static native String Tags_get(long jarg1, Tags jarg1_, String jarg2);
  public final static native void Tags_set(long jarg1, Tags jarg1_, String jarg2, String jarg3);
  public final static native void Tags_del(long jarg1, Tags jarg1_, String jarg2);
  public final static native boolean Tags_has_key(long jarg1, Tags jarg1_, String jarg2);
  public final static native void delete_Tags(long jarg1);
  public final static native void DataSource_update(long jarg1, DataSource jarg1_);
  public final static native void DataSource_clear(long jarg1, DataSource jarg1_);
  public final static native void delete_DataSource(long jarg1);
  public final static native long new_ClientGeoJsonSource(String jarg1, String jarg2);
  public final static native void ClientGeoJsonSource_addData(long jarg1, ClientGeoJsonSource jarg1_, String jarg2);
  public final static native void ClientGeoJsonSource_addPoint(long jarg1, ClientGeoJsonSource jarg1_, long jarg2, Tags jarg2_, double[] jarg3);
  public final static native void ClientGeoJsonSource_addLine(long jarg1, ClientGeoJsonSource jarg1_, long jarg2, Tags jarg2_, double[] jarg3, int jarg4);
  public final static native void ClientGeoJsonSource_addPoly(long jarg1, ClientGeoJsonSource jarg1_, long jarg2, Tags jarg2_, double[] jarg3, int[] jarg4, int jarg5);
  public final static native void ClientGeoJsonSource_clearData(long jarg1, ClientGeoJsonSource jarg1_);
  public final static native void delete_ClientGeoJsonSource(long jarg1);
  public final static native int addDataSource(long jarg1, DataSource jarg1_);
  public final static native void clearDataSource(long jarg1, DataSource jarg1_, boolean jarg2, boolean jarg3);
  public final static native long ClientGeoJsonSource_SWIGSmartPtrUpcast(long jarg1);
}
