/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mapzen.tangram;

public class Tangram {
    public static void addDataSource(DataSource _source) {
        TangramJNI.addDataSource(DataSource.getCPtr(_source), _source);
    }

    public static void clearDataSource(DataSource _source, boolean _data, boolean _tiles) {
        TangramJNI.clearDataSource(DataSource.getCPtr(_source), _source, _data, _tiles);
    }

}
