/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mapzen.tangram;

public class tangram {
  public static Properties getProp() {
    long cPtr = tangramJNI.getProp();
    return (cPtr == 0) ? null : new Properties(cPtr, true);
  }

}
