macro(get_tangram_version)
    file(READ ${CMAKE_CURRENT_SOURCE_DIR}/core/include/tangram/tangram.h VERSION_FILE)

    string(REGEX MATCH "TANGRAM_VERSION_MAJOR ([0-9]*)" _ ${VERSION_FILE})
    set(TANGRAM_VERSION_MAJOR ${CMAKE_MATCH_1})

    string(REGEX MATCH "TANGRAM_VERSION_MINOR ([0-9]*)" _ ${VERSION_FILE})
    set(TANGRAM_VERSION_MINOR ${CMAKE_MATCH_1})

    string(REGEX MATCH "TANGRAM_VERSION_PATCH ([0-9]*)" _ ${VERSION_FILE})
    set(TANGRAM_VERSION_PATCH ${CMAKE_MATCH_1})

    set(TANGRAM_VERSION ${TANGRAM_VERSION_MAJOR}.${TANGRAM_VERSION_MINOR}.${TANGRAM_VERSION_PATCH})
endmacro()
