name: "Windows CI"
on: push
jobs:
  build-test-windows:
    name: "Build and Test on Windows"
    runs-on: windows-2019
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Checkout vcpkg"
        uses: actions/checkout@v2
        with:
          repository: microsoft/vcpkg
          ref: 2021.05.12
          path: vcpkg
      - name: "Cache vcpkg binaries"
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\vcpkg\archives
          key: vcpkg-v2-${{ hashFiles('vcpkg.json') }}
          restore-keys: vcpkg-v1-
      - name: "Configure CMake"
        run: cmake -S . -B .\build -G "Visual Studio 16 2019" \
          -DCMAKE_TOOLCHAIN_FILE=".\vcpkg\scripts\buildsystems\vcpkg.cmake" \
          -DCMAKE_BUILD_TYPE=Debug
          -DTANGRAM_BUILD_TESTS=1
      - name: "Run Build"
        run: cmake --build .\build
      - name: "Run Tests"
        run: .\tests\Debug\tests.out.exe
        working-directory: .\build
